package model.rightpanel;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.swing.JFileChooser;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;

import ij.IJ;
import ij.ImagePlus;
import ij.WindowManager;
import ij.gui.Plot;
import ij.measure.Calibration;
import ij.measure.ResultsTable;
import mainGUI.panels.subpanels.leftpanel.PreprocessingPanel;
import model.workers.measures.MeasuresProcessingWorker;

/**
 * Provides measurements management operations. Indirectly used by the LDC {@link PreprocessingPanel} UI class.
 */
public class MeasurementsManager {

    /**
     * Creates a {@link SwingWorker}, that take care of processing measurements and showing them, if executed.
     * @param minSize minimum particle size (px).
     * @param maxSize maximum particle size (px).
     * @param minCircularity minimum particle circularity.
     * @param maxCircularity maximum particle circularity.
     * @param excludeOnEdgesEnabled Particle Analyzer option.
     * @param showAreaEnabled True if the 'Area' column must be shown in the results.
     * @param showMedianEnabled True if the 'Median' column must be shown in the results.
     * @param showMeanEnabled True if the 'Mean' column must be shown in the results.
     * @param showIntegratedDensityEnabled True if the 'IntegratedDensity' column must be shown in the results.
     * @param showCircularityEnabled True if the 'Circularity' column is shown must be the results.
	 * @see MeasuresProcessingWorker
     */
	public SwingWorker<Void,Void> createMeasuresProcessingWorker(double minSize, double maxSize, double minCircularity, double maxCircularity, boolean excludeOnEdgesEnabled, 
			boolean showAreaEnabled, boolean showMedianEnabled, boolean showMeanEnabled, boolean showIntegratedDensityEnabled, boolean showCircularityEnabled){
		return new MeasuresProcessingWorker(minSize, maxSize, minCircularity, maxCircularity, excludeOnEdgesEnabled, 
				showAreaEnabled, showMedianEnabled, showMeanEnabled, showIntegratedDensityEnabled, showCircularityEnabled); 
	}
	
    /**
     * Export as a CSV file the table passed in parameter. 
     * @param rt the ResultsTable to export as a CSV file.
     * @param path the path of the file as a String.
     */
    public void exportResultsTable(ResultsTable rt, String path) {
    	
    	// check if there is data to export
    	if (rt == null || rt.getCounter() == 0) {
    		IJ.showMessage("No data to export.");
    		return;
    	}
    	
    	// force CSV extension
    	if (!path.toLowerCase().endsWith(".csv")) {
            path += ".csv";
        }

    	// try to save the file
    	if (!rt.save(path)) {
    		IJ.showMessage("An error occured while saving file.");
    	}
    }
    
    /**
     * Calculate the summary ResultTable generated by ImageJ.
     * @param rt the ResultsTable to generate statistics from.
     * @return the ResultsTable containing the statistics.  
     */
    public ResultsTable calculateSummaryTable(ResultsTable rt) {
    	
    	ResultsTable summaryRt = new ResultsTable();
    	
    	if (rt == null || rt.getCounter() == 0) {
    		IJ.showMessage("No data yet.");
    		return summaryRt;
    	}
    	
    	ImagePlus imp = WindowManager.getCurrentImage();
        double totalImageArea = 0;
        
        if (imp != null) {
        	// calculate the total area of the image
            Calibration cal = imp.getCalibration();
            double totalArea = cal.pixelWidth * cal.pixelHeight;
            totalImageArea = imp.getWidth() * imp.getHeight() * totalArea;
        }
        
        // Slice number -> List of indexes of line that corresond to the slice
        Map<Integer, List<Integer>> rowsBySlice = new HashMap<>();
        
        boolean hasSliceCol = rt.columnExists("Slice"); // check if there is a slice column in the table
        
        for (int i = 0; i < rt.getCounter(); i++) {
            // if there is no slice columns, we consider that every rows are in slice 1
            int slice = hasSliceCol ? (int) rt.getValue("Slice", i) : 1;
            rowsBySlice.computeIfAbsent(slice, k -> new ArrayList<>()).add(i);
        }
              
        // columns to compute statistics
        String[] headings = rt.getHeadings();
        boolean hasArea = rt.columnExists("Area");
        
        // columns to ignores
        Set<String> ignoredCols = new HashSet<>(Arrays.asList(
            "Slice", "X", "Y"
        ));
        
        // sorting
        List<Integer> sortedSlices = new ArrayList<>(rowsBySlice.keySet());
        Collections.sort(sortedSlices);
        
        // compute statistics for each list
        for (int slice : sortedSlices) {
        	
        	List<Integer> rows = rowsBySlice.get(slice);
        	int count = rows.size();
        	
        	summaryRt.incrementCounter();
            summaryRt.addValue("Slice", slice);
            summaryRt.addValue("Count", count);
            
            // if area column is present compute its statistics
            if (hasArea) {
                double sumArea = 0;
                for (int row : rows) {
                    sumArea += rt.getValue("Area", row);
                }
                double avgSize = (count > 0) ? sumArea / count : 0;
                double pctArea = (totalImageArea > 0) ? (sumArea / totalImageArea) * 100.0 : 0;

                summaryRt.addValue("Total Area", sumArea);
                summaryRt.addValue("Average Size", avgSize);
                summaryRt.addValue("%Area", pctArea);
            }
            
            for (String col : headings) {
                // skip area because already treated
                if (col.equals("Area") || ignoredCols.contains(col)) {
                    continue;
                }

                // check that the column exists
                if (rt.columnExists(col)) {
                    double sum = 0;
                    int validValues = 0;
                    
                    for (int row : rows) {
                        double val = rt.getValue(col, row);
                        if (!Double.isNaN(val)) {
                            sum += val;
                            validValues++;
                        }
                    }
                    
                    // compute the average
                    double average = (validValues > 0) ? sum / validValues : 0;
                    
                    // add the column to the summary
                    summaryRt.addValue(col, average);
                }
            }
        }

        return summaryRt;
    }
    
    
    /**
     * Generate a list containing histograms for each columns of the ResultsTable.
     * @param rt ResultsTable to generated histograms from.
     * @return List that contain ImagePlus Object of histograms for each column of the table.
     */
    public List<ImagePlus> generateHistograms(ResultsTable rt){
    	
    	List<ImagePlus> plots = new ArrayList<>();
    	
    	// check if the table is null or empty
    	if (rt == null || rt.getCounter() == 0) {
    		IJ.showMessage("No data to generate histograms");
    		return plots;
    	}
    	
    	String[] headings = rt.getHeadings();
    	
    	Set<String> ignored = new HashSet<>(Arrays.asList("Slice"));
    	
    	// compute histograms of each columns
    	for (String col : headings) {
    		if (ignored.contains(col) || !rt.columnExists(col)) continue; // skip if ignored
    		
    		double[] data = rt.getColumn(col);
            if (data == null || data.length == 0) continue; // skip if no data

            // compute MIN MAX statistics
            double min = Double.MAX_VALUE;
            double max = -Double.MAX_VALUE;
            for (double v : data) {
                if (v < min) min = v;
                if (v > max) max = v;
            }
            
            // avoid division by zero
            if (min == max) {
                min -= 1;
                max += 1;
            }

            // bins creation
            int nBins = 20; // arbitrary value
            double binWidth = (max - min) / nBins;
            double[] xValues = new double[nBins];
            double[] yValues = new double[nBins];

            // initialization center X
            for (int i = 0; i < nBins; i++) {
                xValues[i] = min + (i + 0.5) * binWidth;
            }

            // fill frequencies
            for (double v : data) {
                int bin = (int) ((v - min) / binWidth);
                if (bin >= nBins) bin = nBins - 1;
                if (bin < 0) bin = 0;
                yValues[bin]++;
            }

            // create plot ImageJ
            Plot plot = new Plot("Distribution: " + col, col, "Frequency");
            plot.add("bar", xValues, yValues);
            plot.setColor(Color.BLUE);
            plot.setStyle(0, "blue, fill, 1.0"); 
            
            plots.add(plot.getImagePlus());
        }
    	return plots;
    }
}
